name = "cloudd"
main = "_worker.js"
compatibility_date = "2026-06-09"

[vars]
uuid = "56d22e7d-e7a7-41a0-9acd-837b8b6d32ec"
proxyip = ""
cdnip = "www.visa.com.sg"

ip1 = "www.visa.com"
ip2 = "cis.visa.com"
ip3 = "africa.visa.com"
ip4 = "www.visa.com.sg"
ip5 = "www.visaeurope.at"
ip6 = "www.visa.com.mt"
ip7 = "qa.visamiddleeast.com"

ip8 = "usa.visa.com"
ip9 = "myanmar.visa.com"
ip10 = "www.visa.com.tw"
ip11 = "www.visaeurope.ch"
ip12 = "www.visa.com.br"
ip13 = "www.visasoutheasteurope.com"

pt1 = "80"
pt2 = "8080"
pt3 = "8880"
pt4 = "2052"
pt5 = "2082"
pt6 = "2086"
pt7 = "2095"

pt8 = "443"
pt9 = "8443"
pt10 = "2053"
pt11 = "2083"
pt12 = "2087"
pt13 = "2096"
